<a href="https://colab.research.google.com/github/koseogluonur/-Python-for-DataScience-and-Machine-Learning-/blob/main/Data_Manipulation_with_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NumPy**

In [ ]:
import numpy as np

In [ ]:
#Liste üzerinden oluşturma
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [ ]:
a=np.array([1,2,3,4,5])

In [ ]:
type(a)

numpy.ndarray

In [ ]:
#Tek tip bir biçime izin verir.Kendisi ona göre dönüştürür.
np.array([3.14,2,8.18,9])

array([3.14, 2.  , 8.18, 9.  ])

In [ ]:
#Kendin de oluşturabilirsin.
np.array([3.14,2,8.18,9],dtype=int)

array([3, 2, 8, 9])

In [ ]:
#Sıfırdan array oluşturma
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
np.ones((3,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
np.full((3,5),3,dtype=int)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [ ]:
np.arange(0,31,3,dtype=int)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [ ]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
np.random.normal(10,4,(3,4))

array([[ 6.94014553, 14.60568857,  8.89237588, 12.76591914],
       [14.7530851 ,  1.92443184,  8.01223619,  4.92951596],
       [ 7.56178238, 10.95633446,  8.91867747, 11.75238739]])

In [ ]:
np.random.randint(0,10,(3,3))

array([[5, 7, 9],
       [2, 6, 6],
       [1, 7, 5]])

In [ ]:
x=np.random.randint(10,size=10)
x

array([0, 1, 0, 4, 2, 5, 6, 7, 3, 9])

In [ ]:
x.ndim

1

In [ ]:
x.shape

(10,)

In [ ]:
x.size

10

In [ ]:
x.dtype

dtype('int64')

In [ ]:
y=np.random.randint(10,size=(3,5))
y

array([[6, 4, 1, 5, 3],
       [2, 6, 1, 9, 3],
       [2, 3, 4, 4, 9]])

In [ ]:
y.ndim

2

In [ ]:
y.shape

(3, 5)

In [ ]:
y.size

15

In [ ]:
y.dtype

dtype('int64')

In [ ]:
#Reshape(Yeniden Şekillendirme&Boyut değiştirme)
import numpy as np
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
a=np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a.ndim

1

In [ ]:
b=a.reshape(1,9)
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
b.ndim

2

In [ ]:
#Concatenation(Birleştirme)
import numpy as np
x=np.array([1,2,3,4,5])
y=np.array([7,8,9,10])

np.concatenate([x,y])

array([ 1,  2,  3,  4,  5,  7,  8,  9, 10])

In [ ]:
z=np.array([11,12,13])
np.concatenate([x,y,z])

array([ 1,  2,  3,  4,  5,  7,  8,  9, 10, 11, 12, 13])

In [ ]:
#İki Boyutta 
k=np.array([[1,2,3],
           [4,5,6]])
k

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.concatenate([k,k])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.concatenate([k,k],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [ ]:
#Splitting(Array Ayırma)
s=np.array([1,2,3,99,99,3,2,1])
np.split(s,[3,5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [ ]:
#Çıktı atama,oluşturulan grupları bir değere verme
x1,x2,x3=np.split(s,[3,5])
x1

array([1, 2, 3])

In [ ]:
x2

array([99, 99])

In [ ]:
x3

array([3, 2, 1])

In [ ]:
#İki boyutlu ayırma
m=np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
#Yatay ayırma
np.vsplit(m,[2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [ ]:
ust,alt=np.vsplit(m,[2])
ust
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
#Dikine Ayırma
np.hsplit(m,[3])

[array([[ 0,  1,  2],
        [ 4,  5,  6],
        [ 8,  9, 10],
        [12, 13, 14]]), array([[ 3],
        [ 7],
        [11],
        [15]])]

In [ ]:
sag,sol=np.hsplit(m,[3])
sag
sol

array([[ 3],
       [ 7],
       [11],
       [15]])

In [ ]:
#Sorting(Sıralama)
v=np.array([2,3,9,8,7,6,1,0,11,15,3,4,5,6])
v

array([ 2,  3,  9,  8,  7,  6,  1,  0, 11, 15,  3,  4,  5,  6])

In [ ]:
np.sort(v)

array([ 0,  1,  2,  3,  3,  4,  5,  6,  6,  7,  8,  9, 11, 15])

In [ ]:
v

array([ 2,  3,  9,  8,  7,  6,  1,  0, 11, 15,  3,  4,  5,  6])

In [ ]:
v.sort()

In [ ]:
v

array([ 0,  1,  2,  3,  3,  4,  5,  6,  6,  7,  8,  9, 11, 15])

In [ ]:
#İki boyutlu
z=np.random.normal(20,4,(3,3))
z

array([[18.39334655, 16.68392792, 21.97308103],
       [22.38670644, 20.18321893, 26.58309007],
       [19.81209932, 23.83459446, 16.94857798]])

In [ ]:
z.mean()

20.75540474516613

In [ ]:
#Sütun bazlı sıralama
np.sort(z,axis=0)

array([[18.39334655, 16.68392792, 16.94857798],
       [19.81209932, 20.18321893, 21.97308103],
       [22.38670644, 23.83459446, 26.58309007]])

In [ ]:
#Satır bazlı sıralama
np.sort(z,axis=1)

array([[16.68392792, 18.39334655, 21.97308103],
       [20.18321893, 22.38670644, 26.58309007],
       [16.94857798, 19.81209932, 23.83459446]])

**Indexler ve Kümeler Üzerinde İşlemler**

In [ ]:
import numpy as np
a=np.random.randint(10,size=10)
a


array([7, 3, 6, 4, 8, 6, 4, 9, 6, 1])

In [ ]:
a[0]

7

In [ ]:
a[-1]

1

In [ ]:
b=np.random.randint(10,size=(3,5))
b

array([[0, 0, 5, 9, 2],
       [2, 3, 2, 3, 3],
       [4, 3, 0, 5, 3]])

In [ ]:
#Satır da sütünlarda tıpkı arraylarde olduğu gibi 0 ile başlar
b[0,0]

0

In [ ]:
b[2,4]

3

In [ ]:
#NumPy standart veri tipine sahip olduğu için ekleme yapsan bile o veri tipine dönüştürür.
b[1,4]=4.8
b

array([[0, 0, 5, 9, 2],
       [2, 3, 2, 3, 4],
       [4, 3, 0, 5, 3]])

In [ ]:
#Slicing(Array Alt Küme İşlemleri)
x=np.arange(20,30,dtype=int)
x

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [ ]:
x[0:3]

array([20, 21, 22])

In [ ]:
x[:4]

array([20, 21, 22, 23])

In [ ]:
x[:-1]

array([20, 21, 22, 23, 24, 25, 26, 27, 28])

In [ ]:
x[5:]

array([25, 26, 27, 28, 29])

In [ ]:
x[1::2]

array([21, 23, 25, 27, 29])

In [ ]:
x[2::3]

array([22, 25, 28])

In [ ]:
y=np.random.randint(10,size=(5,5))
y

array([[9, 9, 2, 7, 1],
       [8, 4, 2, 3, 8],
       [3, 1, 9, 4, 0],
       [6, 2, 7, 1, 8],
       [4, 7, 5, 6, 9]])

In [ ]:
y[:,0]

array([9, 8, 3, 6, 4])

In [ ]:
y[:,3]

array([7, 3, 4, 1, 6])

In [ ]:
y[0,:]

array([9, 9, 2, 7, 1])

In [ ]:
y[0:2,0:3]

array([[9, 9, 2],
       [8, 4, 2]])

In [ ]:
y[2:4,1:4

array([[1, 9, 4],
       [2, 7, 1]])

In [ ]:
y[::,0:2]

array([[9, 9],
       [8, 4],
       [3, 1],
       [6, 2],
       [4, 7]])

In [ ]:
y[0:3,::]

array([[9, 9, 2, 7, 1],
       [8, 4, 2, 3, 8],
       [3, 1, 9, 4, 0]])

In [ ]:
#Alt küme üzerinde işlem yapmak
t=np.random.randint(10,size=(5,5))
t

array([[7, 1, 7, 4, 1],
       [4, 0, 6, 5, 0],
       [7, 2, 1, 1, 3],
       [3, 5, 1, 2, 3],
       [1, 7, 5, 9, 0]])

In [ ]:
t_altkume=t[0:3,0:2]
t_altkume

array([[7, 1],
       [4, 0],
       [7, 2]])

In [ ]:
t_altkume[0,0]=15
t_altkume[2,1]=10
t_altkume

array([[15,  1],
       [ 4,  0],
       [ 7, 10]])

In [ ]:
t
#Alt kümede yapılmış olan değişiklik üst kümede de gerçekleşir.

array([[15,  1,  7,  4,  1],
       [ 4,  0,  6,  5,  0],
       [ 7, 10,  1,  1,  3],
       [ 3,  5,  1,  2,  3],
       [ 1,  7,  5,  9,  0]])

In [ ]:
#Eğer sadece alt kümede işlem yapmak istiyorsak copy fonksiyonu kullanılır
#Üst kümede işlem değişmemiş olur.
z=np.random.randint(10,size=(5,5))
z

array([[1, 4, 3, 9, 8],
       [8, 6, 0, 8, 2],
       [0, 7, 8, 7, 3],
       [6, 5, 3, 1, 2],
       [2, 7, 6, 1, 7]])

In [ ]:
z_altkume=z[0:3,0:2].copy()
z_altkume


array([[1, 4],
       [8, 6],
       [0, 7]])

In [ ]:
z_altkume[1,1]=5
z_altkume

array([[1, 4],
       [8, 5],
       [0, 7]])

In [ ]:
z

array([[1, 4, 3, 9, 8],
       [8, 6, 0, 8, 2],
       [0, 7, 8, 7, 3],
       [6, 5, 3, 1, 2],
       [2, 7, 6, 1, 7]])

In [ ]:
#Fancy Index
v=np.arange(0,30,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [ ]:
v[1]

3

In [ ]:
v[3]

9

In [ ]:
v[5]

15

In [ ]:
v[1],v[3],v[5]

(3, 9, 15)

In [ ]:
al_getir=[1,3,5]
v[al_getir]

array([ 3,  9, 15])

In [ ]:
#İki boyutta fancy
u=np.arange(9).reshape(3,3)
u

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
satır=np.array([0,1])
sutun=np.array([1,2])
u[satır,sutun]

array([1, 5])

In [ ]:
#Basit index ile Fancy index birlikte kullanımı

In [ ]:
u[0,[1,2]]

array([1, 2])

In [ ]:
#Slice ile fancy
u[0:,[1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [1]:
import numpy as np
v=np.array([1,2,3,4,5])
v

array([1, 2, 3, 4, 5])

In [2]:
v>5

array([False, False, False, False, False])

In [3]:
v<3

array([ True,  True, False, False, False])

In [4]:
v[v<3]

array([1, 2])

In [5]:
v[v!=4]

array([1, 2, 3, 5])

In [6]:
v*2

array([ 2,  4,  6,  8, 10])

In [7]:
v/5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [ ]:
#Matematiksel İşlemler
#Operatörle yapılacağı gib ufunctionlarla da yapılır

In [8]:
#Operator
v-1

array([0, 1, 2, 3, 4])

In [9]:
#Ufunction
np.subtract(v,1)

array([0, 1, 2, 3, 4])

In [10]:
np.add(v,2)

array([3, 4, 5, 6, 7])

In [11]:
np.multiply(v,3)

array([ 3,  6,  9, 12, 15])

In [13]:
np.divide(v,4)

array([0.25, 0.5 , 0.75, 1.  , 1.25])

In [14]:
np.power(v,2)

array([ 1,  4,  9, 16, 25])

In [16]:
np.mod(v,2)

array([1, 0, 1, 0, 1])

In [17]:
np.absolute(v)

array([1, 2, 3, 4, 5])

In [18]:
np.sin(180)

-0.8011526357338304

In [19]:
np.cos(90)

-0.4480736161291701

In [20]:
np.log(v)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [21]:
np.log2(v)

array([0.        , 1.        , 1.5849625 , 2.        , 2.32192809])

In [22]:
#numPY hakkındaki paketleri ve daha fazla bilgi edinmek için:
?np
#Ya da google

In [ ]:
#cheatsheet
Hem Python Hem R cheat sheetleri internetten bulup indirebilirsin.

In [ ]:
#Statistics
np.mean(arr,axis=0) | Returns mean along specific axis
arr.sum() | Returns sum of arr
arr.min() | Returns minimum value of arr
arr.max(axis=0) | Returns maximum value of specific axis
np.var(arr) | Returns the variance of array
np.std(arr,axis=1) | Returns the standard deviation of specific axis
arr.corrcoef() | Returns correlation coefficient of array

In [23]:
np.mean(v,axis=0)

3.0

In [24]:
v.sum()

15

In [25]:
v.min()

1

In [ ]:
#İki bilinmeyenli denklemin çözümü
import numpy as np
5*x0+x1=12
x0+3*x1=10

In [27]:
a=np.array([[5,1],[1,3]])
b=np.array([12,10])

In [28]:
a

array([[5, 1],
       [1, 3]])

In [29]:
b

array([12, 10])

In [30]:
x=np.linalg.solve(a,b)
x

array([1.85714286, 2.71428571])

In [40]:
m=np.array([[0, 1, 2],

             [3, 4, 5],

             [6, 7, 8]])

m[0:, [1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])